Complete rewrite of this script: * Replacing old code with more mature, modern, clean code. * Now uses a config file instead of case statements to select data files. Eww! * Tested for use with sudo so one doesn't need to become root every time they want to use it.

diff --git a/safe b/safe
--- a/safe
+++ b/safe
@@ -1,50 +1,26 @@
 #!/bin/bash
 
-# Create a data file, encrypt it with cryptsetup, format it with
-# a filesystem and use 'safe' to easily open it and mount it for use,
-# then unmount and lock it for secure and safe keeping.
-
-# The primary purpose of this process is to keep data encrypted and
-# secure most of the time.  Unlock it when you need it and lock it quickly
-# afterwards.  If someone breaks into your system, they'll likely
-# get away with encrypted data, but not raw data files of important
-# information.
-
-# This script must be run as root on some systems including Fedora 20
-# because, it seems, of the way cryptsetup is built on those systems.
-
-# See the github safe.md documentation for more information.
-
-###################################################################
-# Copyright 2014 Maxwell Spangler, maxwell@maxwellspangler.com
-
-# This program is free software; you can redistribute it and/or
-# modify it under the terms of the GNU General Public License
-# as published by the Free Software Foundation; either version 2
-# of the License, or (at your option) any later version.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the 
-# Free Software Foundation, Inc., 
-# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
-###################################################################
-
 # Our version, update as changes are made.
-VERSION="2014.0309.01"
+VERSION="2.0.0"
+VERSION="2019.1224.01"
 
-# Static: define list of all safe names here. 
-SAFE_LIST="notes legal personal"
+CONFIG_FILE=/home/${USERNAME}/.safe.conf
+
+# Global Scope
+SAFE_DIRECTORY=""
+SAFE_INFO=""
+SAFE_NAME=""
+SAFE_USER=""
+SAFE_MAPPER=""
+SAFE_MOUNT=""
+SAFE_FILENAME=""
+SAFE_OPEN="no"
 
 function usage {
 	echo
-	echo "safe $VERSION"
+	echo "safe $VERSION $VERSION_DATE"
 	echo
-	echo "Syntax: safe [list] [open|close|status] <safename|all>"
+	echo "Syntax: safe [list] [open|close|status] <safename>"
 	echo
 	echo "'open'   - open a safe"
 	echo "'close'  - close a safe"
@@ -55,349 +31,284 @@ function usage {
 	echo
 }
 
-function list_safes {
+function validate_config_file {
 
-	echo "'Safe' currently knows about these safes:"
-	for EACH_SAFE in $SAFE_LIST
-	do
-		echo  "	-> '$EACH_SAFE'"
-	done
-	echo
-}
-
-# Set the two command line parameters: action and safe name
-ACTION=${1:-"null"}
-SAFE_NAME=${2:-"null"}
-
-# If the user issues 'safe status' convert it to 'safe status all'
-if [[ $ACTION == "status" || $ACTION == "list" ]] && [[ $SAFE_NAME == "null" ]]
-then
-	SAFE_NAME="all"
-fi
-
-if [[ $ACTION != "open" && $ACTION != "close" && $ACTION != "list" && $ACTION != "status" ]]
-then
-	echo "You must specify an action of 'list', 'status', 'open' or 'close'"
-	usage
-	exit 1
-fi
-
-if [[ $SAFE_NAME == "null" ]]
-then
-	echo "You must specify a valid safe name."
-	usage
-	exit 1
-fi
-
-# Check for $2 within $1. Return 0 if not found, or position of $2
-function strindex { 
-  x="${1%%$2*}"
-  [[ $x = $1 ]] && echo -1 || echo ${#x}
-}
-
-# Check for user supplied safe name within list of defined safes
-if [[ $SAFE_NAME != "all" ]]
-then
-
-	SAFE_CHECK=$(strindex "$SAFE_LIST" "$SAFE_NAME")
-
-	if [[ $? == -1 ]]
+	if [[ ! -r $CONFIG_FILE ]]
 	then
-		echo "You must specify a valid safe name."
-		usage
+		if [[ ! -f $CONFIG_FILE ]]
+		then
+			echo "ERROR: Config file $CONFIG_FILE does not exist."
+		else
+			echo "ERROR: Config file $CONFIG_FILE is not readable."
+		fi
+  fi
+}
+
+function get_safe_directory {
+	SAFE_DIRECTORY=""
+
+	SD_COUNT=$(egrep '^safe_directory' $CONFIG_FILE | wc -l)
+	if [[ $SD_COUNT == 0 ]]
+	then
+		echo "ERROR: There are no 'safe_directory' declarations in $CONFIG_FILE"
 		exit 1
 	fi
-fi
 
-# Associate a safe name with required parameters in set_safe_parameters
-function set_safe_parameters {
+	if [[ $SD_COUNT -gt 1 ]]
+	then
+		echo "ERROR: There are more then one 'safe_directory' declarations in $CONFIG_FILE"
+		exit 1
+	fi
 
-	# default our return variable to error, set it when good
-	SET_SAFE_RETURN="error"
+	SAFE_DIRECTORY=$(egrep '^safe_directory' $CONFIG_FILE | awk '{print $2}')
 
-#
-# This case statement works for now but will be converted into
-# an external config file of some sort in the future.
-#
+}
 
-	case $SAFE_NAME in
+function get_safe_info {
 
-		# Private notes
-		"notes")
-			# only user who can access them
-			USER="maxwell"
+	if [[ -z $1 ]]
+	then
+		echo "ERROR: No safe name passed to get_safe_info"
+		exit 1
+	else
+		VALID_SAFE=false
+		SAFE_INFO=""
+		SAFE_NAME=""
+		SAFE_USER=""
+		SAFE_MAPPER=""
+		SAFE_MOUNT=""
+		SAFE_FILENAME=""
+		SAFE_OPEN="no"
 
-			# Location of encrypted LUKS file
-			SOURCE_FILE="/home/maxwell/Documents/Safes/notes.luks"
+		FOUND_COUNT=$(egrep '^safe_file' $CONFIG_FILE | grep $1 | wc -l)
 
-			# Unlock with LUKS and map to this in /dev/mapper
-			UNLOCKED_MAPPING="notes-luks"
+		if [[ $FOUND_COUNT == 1 ]]
+		then
+			VALID_SAFE=true
 
-			# Mount the filesystem at this location
-			MOUNT_POINT="/mnt/secure/notes"
+			SAFE_INFO=$(egrep '^safe_file' $CONFIG_FILE | grep $1)
 
-			SET_SAFE_RETURN="success";;
+			SAFE_NAME=$(echo $SAFE_INFO | awk '{print $2}')
+			SAFE_USER=$(echo $SAFE_INFO | awk '{print $3}')
+			SAFE_MAPPER=$(echo $SAFE_INFO | awk '{print $4}')
+			SAFE_MOUNT=$(echo $SAFE_INFO | awk '{print $5}')
+			SAFE_FILENAME=$(echo $SAFE_INFO | awk '{print $6}')
 
-		# Legal Documents
-		"legal")
-			# only user who can access them
-			USER="maxwell"
+			if [[ -h /dev/mapper/$SAFE_MAPPER ]]
+			then
+				SAFE_OPEN="yes"
+			else
+				SAFE_OPEN="no"
+			fi
+		fi
+	fi
+}
 
-			# Location of encrypted LUKS file
-			SOURCE_FILE="/home/maxwell/Documents/Safes/legal.luks"
+function report_header {
+	printf "%-10s %-4s %-10s %-15s %-25s %-15s\n" "Safe" "Open" "User" "Map Name" "Mount point" "Filename"
+	printf "%-10s %-4s %-10s %-15s %-25s %-15s\n" "----" "----" "----" "--------" "-----------" "--------"
+}
 
-			# Unlock with LUKS and map to this in /dev/mapper
-			UNLOCKED_MAPPING="legal-luks"
+function report_detail {
+	printf "%-10s %-4s %-10s %-15s %-25s %-15s\n" $SAFE_NAME $SAFE_OPEN $SAFE_USER $SAFE_MAPPER $SAFE_MOUNT $SAFE_FILENAME
+}
 
-			# Mount the filesystem at this location
-			MOUNT_POINT="/mnt/secure/legal"
+function list_safes {
 
-			SET_SAFE_RETURN="success";;
-
-		# Personal Documents
-		"personal")
-			# only user who can access them
-			USER="maxwell"
-
-			# Location of encrypted LUKS file
-			SOURCE_FILE="/home/maxwell/Documents/Safes/personal.luks"
-
-			# Unlock with LUKS and map to this in /dev/mapper
-			UNLOCKED_MAPPING="personal-luks"
-
-			# Mount the filesystem at this location
-			MOUNT_POINT="/mnt/secure/personal"
-
-			SET_SAFE_RETURN="success";;
-
-		*)
-			# This function has been called with an unknown safe, return error
-			SET_SAFE_RETURN="error"
-
-	esac
-
+	FILE_COUNT=$(egrep '^safe_file' $CONFIG_FILE | awk {'print $2'} | wc -l)
+	if [[ $FILE_COUNT == 0 ]]
+  then
+		echo "ERROR: There are no safes defined as 'safe_file' items in $CONFIG_FILE"
+		exit 1
+  else
+		report_header
+		FILE_LIST=$(egrep '^safe_file' $CONFIG_FILE | awk {'print $2'})
+		for EACH_SAVE in $FILE_LIST
+		do
+			get_safe_info $EACH_SAVE
+			report_detail
+		done
+  fi
 }
 
 # Open a single safe data file
 function open_safe {
 
-	# Before opening, see if we have a source data file to open
-	if [[ ! -f "$SOURCE_FILE" ]]
+	get_safe_info $1
+
+	if [[ $VALID_SAFE == no ]]
 	then
-		echo "I can't locate a data file for safe $SAFE_NAME at $SOURCE_FILE"
+		echo "ERROR: $1 is not a valid safe that can be opened"
+		exit 1
 	else
 
-		# Is the safe unlocked?
-		if [[ -h /dev/mapper/$UNLOCKED_MAPPING ]]
+		if [[ $SAFE_OPEN == "yes" ]]
 		then
-
-#		# See if the safe is already open and in use
-#		STATUS=$(cryptsetup status $UNLOCKED_MAPPING | grep "is in use" | wc -l)
-
-		# If already open, report to user and show some use information
-		#if [[ $STATUS -gt 0 ]]
-		#then
-
-			echo "Safe $SAFE_NAME is already open."
-			cryptsetup status $UNLOCKED_MAPPING
-
-		else
-
-			# Unlock the encrypted file's contents
-			cryptsetup luksOpen $SOURCE_FILE $UNLOCKED_MAPPING
-
-			# If the unlock operation was not successful, report to user
-			# Note: this is in addition to cryptsetup's own error reporting
-			if (( $? != 0 ))
-			then
-				echo "Error $?"
-				echo "Unable to open $SOURCE_FILE"
-				exit 1
-
-			fi
-
+			echo "ERROR: Safe $1 is already open"
+			status_safe $1
+			exit 1
 		fi
 
-		# See if the safe is mounted. If yes, we'll try to unmount it
-		if [[ $(mount | grep $UNLOCKED_MAPPING | grep $MOUNT_POINT | wc -l) -gt 0 ]]
+		if [[ ! -r $SAFE_DIRECTORY/$SAFE_FILENAME ]]
 		then
-			echo "Safe '$SAFE_NAME' is already mounted at $UNLOCKED_MAPPING"
-
-		else
-
-			# If the mount point does not exist, let's try to make it.
-			if [[ ! -d $MOUNT_POINT ]]
+			if [[ ! -f $SAFE_DIRECTORY/$SAFE_FILENAME ]]
 			then
-
-				# Check to see if we have a /mnt directory
-				# If we don't, don't make one.
-				if [[ -d /mnt ]]
-				then
-
-					# We have mnt, but maybe nothing else, so make it.
-					mkdir -p $MOUNT_POINT
-
-					# Change the owner of this mount point to our explicit user
-					chown $USER $MOUNT_POINT
-
-					# Disallow access by any other users
-					chmod og-rwx $MOUNT_POINT
-				else
-
-					# We can't make a directory in /mnt because no /mnt
-					echo "ERROR: There is no /mnt directory on this system."
-					exit 1
-				fi
-				echo "WARNING: Created $MOUNT_POINT for you."
-			fi
-
-			# Mount the unlocked file's embedded filesystem
-			mount /dev/mapper/$UNLOCKED_MAPPING $MOUNT_POINT
-
-			# If the mount was unsuccessful, handle the error
-			if (( $? != 0 ))
-			then
-				echo "Unable to mount $UNLOCKED_MAPPING at $MOUNT_POINT"
+				echo "ERROR: Safe file $SAFE_FILENAME does not exist"
 				exit 1
 			else
+				echo "ERROR: Safe file $SAFE_FILENAME is not readable"
+				exit 1
+			fi
+		fi
 
-				# Success: Filesystem data is now available.
-				echo "Your files are now available at $MOUNT_POINT"
-				echo "Issue safe-close $SAFE_NAME to close it"
-				echo
+		cryptsetup luksOpen $SAFE_DIRECTORY/$SAFE_FILENAME $SAFE_MAPPER
 
+		if [[ $? != 0 ]]
+		then
+			echo "ERROR $? while using cryptsetup to open $1 at $SAFE_DIRECTORY/$SAFE_FILENAME"
+			exit 1
+		fi
+
+		if [[ $(mount | grep $SAFE_MOUNT | wc -l) -gt 0 ]]
+		then
+			echo "ERROR: Something is already mounted at $SAFE_MOUNT"
+			echo
+			mount | grep $SAFE_MOUNT
+			exit 1
+		else
+
+			if [[ ! -d $SAFE_MOUNT ]]
+			then
+				echo "Info: Mount point $SAFE_MOUNT does not exist.  Creating it now."
+				mkdir -p $MOUNT_POINT
+				echo "Setting owner of $SAFE_MOUNT as $SAFE_USER"
+				chown $SAFE_USER $MOUNT_POINT
+				echo "Setting security permissions to exclude others on $SAFE_MOUNT"
+				chmod og-rwx $MOUNT_POINT
 			fi
 
-		fi # Block: Attempt to mount safe
+			mount /dev/mapper/$SAFE_MAPPER $SAFE_MOUNT
 
-	fi # block: Check to see if SOURCE_FILE for safe exists
+			if [[ $? != 0 ]]
+			then
+				echo "ERROR: Unable to mount $SAFE_MAPPER at $SAFE_MOUNT"
+				exit 1
+			else
+				mount | grep $SAFE_MOUNT
+				echo
+				echo "Your files are now available at $SAFE_MOUNT"
+				echo "REMEMBER TO CLOSE IT with: 'safe close $1'"
+			fi
+		fi
+	fi
 }
 
-# Close a single safe data file
 function close_safe {
 
-	# Close process:
-	#   - Check to see if the safe is open.  If closed we do nothing.
-	#   - If the safe is open:
-	#   -   Check to see if its mounted.  If mounted, unmount.
-	#   -   Lock the safe to secure the data
+	get_safe_info $1
 
-	# Is the safe unlocked?
-	if [[ -h /dev/mapper/$UNLOCKED_MAPPING ]]
+	if [[ $VALID_SAFE == false ]]
 	then
+		echo "ERROR: $1 is not a valid safe for closing."
+		exit 1
+	fi
 
-		# See if the safe is mounted. If yes, we'll try to unmount it
-		if [[ $(mount | grep $UNLOCKED_MAPPING | grep $MOUNT_POINT | wc -l) -gt 0 ]]
-		then
+	if [[ $SAFE_OPEN == "no" ]]
+	then
+		echo "ERROR: This safe does not appear to be open"
+		echo "Mapper check:"
+		ls -ld /dev/mapper/$SAFE_MAPPER
+		echo "Mount check:"
+		mount | grep $SAFE_MAPPER
+	fi
 
-			# Attempt to unmount
-			umount "$MOUNT_POINT"
-
-			# Handle errors resulting from the unmount
-			if (( $? != 0 ))
-			then
-				echo "Unable to unmount $MOUNT_POINT"
-			fi
-		else
-			echo "The safe is unlocked but not mounted. Skipping unmount."
-		fi
-
-		# Close the safe to secure it
-		cryptsetup luksClose $UNLOCKED_MAPPING
-
-		# Handle errors resulting from our close
-		if (( $? != 0 ))
-		then
-			echo "Unable to unmount $MOUNT_POINT"
-		else
-
-			echo "The safe $SAFE_NAME is now closed and locked."
-			echo
-		fi
-
+	umount $SAFE_MOUNT
+	if [[ $? != 0 ]]
+	then
+		echo "ERROR: $? while trying to unmont $SAFE_MOUNT"
+		exit 1
 	else
+		echo "Mount check after unmounting:"
+		mount | grep $SAFE_MOUNT
+	fi
 
-		echo -e "\nSafe '$SAFE_NAME' is not currently open."
-
+	cryptsetup luksClose $SAFE_MAPPER
+	if [[ $? != 0 ]]
+	then
+		echo "ERROR: $? while trying to luksClose $SAFE_MAPPER"
+		exit 1
+	else
+		status_safe $1
 	fi
 }
 
 # Report the status of a safe
 function status_safe {
 
-	echo -e "\n== Safe '$SAFE_NAME' =="
-
-	if [[ -h /dev/mapper/$UNLOCKED_MAPPING ]]
+	get_safe_info $1
+	if [[ $VALID_SAFE == true ]]
 	then
-
-		# Report the detailed status via cryptsetup
-		cryptsetup status $UNLOCKED_MAPPING
-
-		mount | grep $UNLOCKED_MAPPING
-
-	else
-
-		echo -e "\nSafe '$SAFE_NAME' is not currently open."
-
-	fi
-
-}
-
-# Actions are taken by iterating on all safes in SAFE_LIST.
-# This list is defined earlier just above set_safe_parameters
-# If the user did not specify "all" safes, then set the value of
-# SAFE_LIST to the single user specified safe name
-# and we will iterate over that single safe file with our actions.
-if [[ $SAFE_NAME != "all" ]]
-then
-	# Replace list of all safes with the single user specified safe name
-	SAFE_LIST=$SAFE_NAME
-fi
-
-# Go through list of safes defined in SAFE_LIST
-for EACH_SAFE in $SAFE_LIST
-do
-
-	# Act as though user specified a safe name
-	SAFE_NAME=$EACH_SAFE
-
-	# Set the related safe parameters
-	set_safe_parameters
-
-	# If we were able to set safe parameters
-	if [[ $SET_SAFE_RETURN == "success" ]]
-	then
-
-		# Open or Close?
-		case $ACTION in
-
-			# Open a safe
-			"open")
-				open_safe;;
-
-			# Close a safe
-			"close")
-				close_safe;;
-
-			# List the status of a safe
-			"status")
-				status_safe;;
-
-			# List known safes
-			"list")
-				list_safes
-
-				# Instead of iterating over each item in $SAFE_LIST
-				# as we do for all other commands, we'll call list_safes
-				# once then break out and exit.
-				break;;
-
-		esac
-
-	else
-		echo "I don't know of a safe called '$SAFE_NAME'"
+		report_header
+		report_detail
 		echo
 
+		if [[ ! -r $SAFE_DIRECTORY/$SAFE_FILENAME ]]
+		then
+			if [[ ! -f $SAFE_DIRECTORY/$SAFE_FILENAME ]]
+			then
+				echo "ERROR: Safe file $SAFE_DIRECTORY/$SAFE_FILENAME does not exist"
+			else
+				echo "ERROR: Safe file $SAFE_DIRECTORY/$SAFE_FILENAME is not readable"
+			fi
+		else
+			ls -lh $SAFE_DIRECTORY/$SAFE_FILENAME
+		fi
+		echo
+		echo "Cryptsetup status:"
+		cryptsetup status $SAFE_MAPPER
+	else
+		echo "ERROR: Safe $1 is not a recognized safe name."
 	fi
+}
 
-done # iterate over each safe in SAFE_LIST loop
+#
+# Main Operation
+#
+
+validate_config_file
+
+get_safe_directory
+
+PARM1=${1:-"_null"}
+if [[ $PARM1 == "_null" ]]
+then
+	echo "ERROR: Please specify an action."
+	usage
+	exit 1
+else
+
+	case $PARM1 in
+
+		"open")
+			shift
+			open_safe $1;;
+
+		"close")
+			shift
+			close_safe $1;;
+
+		"status")
+			shift
+			status_safe $1;;
+
+		# List known safes
+		"list")
+			list_safes;;
+
+		*)
+		echo "ERROR: I don't know what $1 means."
+		usage
+		exit 1;
+
+	esac
+fi
